LJHHKF/KHFinal_CODED

BackEnd/Coded/src/main/java/kh/coded/repositories/MemberDAO.java

memberdao modi

---

BackEnd/Coded/src/main/java/kh/coded/repositories/MemberDAO.java
BackEnd/Coded/src/main/resources/application.properties
BackEnd/Coded/src/main/resources/mapper/member-mapper.xml

member-mapper modi, memberdao modi

member-mapper modi, memberdao modi

---

BackEnd/Coded/src/main/resources/mapper/member-mapper.xml

member-mapper modi

---

BackEnd/Coded/src/main/java/kh/coded/controllers/FeedPostController.java
BackEnd/Coded/src/main/java/kh/coded/repositories/FeedPostDAO.java
BackEnd/Coded/src/main/java/kh/coded/services/FeedPostService.java
BackEnd/Coded/src/main/resources/mapper/feed-mapper.xml
FrontEnd/coded/src/App.js
FrontEnd/coded/src/component/feed/FeedList.js

feedlist sample

---

BackEnd/Coded/src/main/java/kh/coded/controllers/FeedPostController.java
BackEnd/Coded/src/main/java/kh/coded/securityconfig/SecurityConfiguration.java
FrontEnd/coded/src/component/feed/FeedList.js
FrontEnd/coded/src/component/feed/FeedPostStyled.js
FrontEnd/coded/src/component/user/MyProfile/MyProfileTemplate.js

fixed autherification

---

BackEnd/Coded/src/main/java/kh/coded/config/Settings.java
BackEnd/Coded/src/main/java/kh/coded/controllers/FeedPostController.java
BackEnd/Coded/src/main/java/kh/coded/services/FeedPostService.java
BackEnd/Coded/src/main/java/utils/StaticValue.java

relocate settings

---

BackEnd/Coded/src/main/java/kh/coded/dto/FeedPostDTO.java
BackEnd/Coded/src/main/java/kh/coded/dto/FollowDTO.java
BackEnd/Coded/src/main/java/kh/coded/dto/PhotoDTO.java
BackEnd/Coded/src/main/java/kh/coded/dto/PostHashsDTO.java
BackEnd/Coded/src/main/java/kh/coded/dto/TodayWeatherDTO.java
BackEnd/Coded/src/main/java/kh/coded/repositories/FeedPostDAO.java
BackEnd/Coded/src/main/resources/mapper/feedpost-mapper.xml

feedpost-mapper , feedpostdao 수정

feedpost-mapper , feedpostdao 수정

---

BackEnd/Coded/src/main/java/kh/coded/controllers/MyPickController.java
BackEnd/Coded/src/main/java/kh/coded/repositories/FeedPostDAO.java
BackEnd/Coded/src/main/java/kh/coded/services/FeedPostService.java
BackEnd/Coded/src/main/resources/mapper/feedpost-mapper.xml

MyPickController

---

BackEnd/Coded/src/main/java/kh/coded/controllers/FeedPostController.java
BackEnd/Coded/src/main/java/kh/coded/repositories/FeedPostDAO.java
BackEnd/Coded/src/main/java/kh/coded/repositories/MemberDAO.java
BackEnd/Coded/src/main/java/kh/coded/services/FeedPostService.java
BackEnd/Coded/src/main/java/kh/coded/services/MemberService.java
BackEnd/Coded/src/main/resources/mapper/feedpost-mapper.xml
BackEnd/Coded/src/main/resources/mapper/member-mapper.xml

검색 기능 (구현중...)

---

BackEnd/Coded/src/main/java/kh/coded/controllers/FeedPostController.java

feedpostcontroller 수정

---

BackEnd/Coded/src/main/java/kh/coded/controllers/AuthenticationController.java
BackEnd/Coded/src/main/java/kh/coded/repositories/MemberDAO.java
BackEnd/Coded/src/main/java/kh/coded/security/oauth/OAuth2UserService.java
BackEnd/Coded/src/main/java/kh/coded/securityconfig/SecurityConfiguration.java
BackEnd/Coded/src/main/java/kh/coded/services/MemberService.java
BackEnd/Coded/src/main/resources/mapper/member-mapper.xml

네이버 로그인 구현

---

BackEnd/Coded/pom.xml
BackEnd/Coded/src/main/java/kh/coded/config/WebSocketConfig.java
BackEnd/Coded/src/main/java/kh/coded/securityconfig/SecurityConfiguration.java
FrontEnd/coded/src/pages/DM/DMPage.js

test websocket

---

BackEnd/Coded/src/main/java/kh/coded/services/FeedPostService.java
BackEnd/Coded/src/main/resources/mapper/photo-mapper.xml
FrontEnd/coded/src/Component/FeedPostDetail/FeedPostDetail.js
FrontEnd/coded/src/pages/ootd/Main/Modal.js

fixed link

---

FrontEnd/coded/src/pages/ootd/Main/Modal.js
FrontEnd/coded/src/pages/ootd/Main/Modal.scss

modal.js, modal.scss 수정

---

FrontEnd/coded/src/component/Navbar/Navbar.js
FrontEnd/coded/src/component/Search/SearchBox.js
FrontEnd/coded/src/component/Search/SearchBox.module.scss

fix weeklydata

---

BackEnd/Coded/src/main/java/kh/coded/controllers/FeedPostController.java
BackEnd/Coded/src/main/java/kh/coded/repositories/PhotoDAO.java
BackEnd/Coded/src/main/java/kh/coded/services/PhotoService.java

photoService, photoDAO, FeedPostController 수정

photoService, photoDAO, FeedPostController 수정

---

BackEnd/Coded/src/main/java/kh/coded/controllers/FeedPostController.java
BackEnd/Coded/src/main/java/kh/coded/services/FeedPostService.java

피드 상세페이지 출력 수정

---

BackEnd/Coded/src/main/java/kh/coded/controllers/FeedPostController.java
BackEnd/Coded/src/main/java/kh/coded/repositories/FeedPostDAO.java
BackEnd/Coded/src/main/java/kh/coded/repositories/MemberDAO.java
BackEnd/Coded/src/main/java/kh/coded/services/FeedPostService.java
BackEnd/Coded/src/main/java/kh/coded/services/MemberService.java

피드 수정,삭제 / 닉네임검색 수정

---

BackEnd/Coded/src/main/resources/mapper/feedpost-mapper.xml

feedpost-mapper 추가

---

BackEnd/Coded/src/main/java/kh/coded/controllers/FeedPostController.java
BackEnd/Coded/src/main/java/kh/coded/repositories/FeedLikeDAO.java
BackEnd/Coded/src/main/java/kh/coded/repositories/FeedPostDAO.java
BackEnd/Coded/src/main/java/kh/coded/services/FeedPostService.java
BackEnd/Coded/src/main/resources/mapper/feedlike-mapper.xml
BackEnd/Coded/src/main/resources/mapper/feedpost-mapper.xml

피드 좋아요 기능 구현

---

BackEnd/Coded/src/main/java/kh/coded/controllers/FeedPostController.java
BackEnd/Coded/src/main/java/kh/coded/services/FeedPostService.java

피드 좋아요 기능 수정

---

BackEnd/Coded/src/main/java/kh/coded/controllers/FeedPostController.java
BackEnd/Coded/src/main/resources/mapper/feedpost-mapper.xml
FrontEnd/coded/src/component/Search/SearchBox.js

complete searchFeed

---

BackEnd/Coded/src/main/java/kh/coded/controllers/FeedPostController.java
BackEnd/Coded/src/main/java/kh/coded/controllers/HashTagController.java
BackEnd/Coded/src/main/resources/mapper/feedpost-mapper.xml
FrontEnd/coded/src/IndexPage.js

Kdy workspace

---

FrontEnd/coded/src/Styles/GlobalStyles.js
FrontEnd/coded/src/component/FeedList/FeedList.js
FrontEnd/coded/src/component/FeedPostDetail/FeedPostDetail.js
FrontEnd/coded/src/component/Navbar/NavbarNonMem.js
FrontEnd/coded/src/component/Navbar/NavbarNonMem.scss
FrontEnd/coded/src/component/Navbar/NavbarOotd/NavbarOotd.js
FrontEnd/coded/src/component/Navbar/NavbarOotd/NavbarOotd.scss
FrontEnd/coded/src/component/Navbar/NavbarWeekly/NavbarWeekly.js
FrontEnd/coded/src/component/Navbar/NavbarWeekly/NavbarWeekly.scss
FrontEnd/coded/src/component/Profile/Component/Footer/Footer.js
FrontEnd/coded/src/component/Profile/Component/Footer/Footer.scss
FrontEnd/coded/src/component/Profile/Profile.js
FrontEnd/coded/src/component/Profile/Profile.scss
FrontEnd/coded/src/component/Profile/ProfileForm.js
FrontEnd/coded/src/component/Profile/ProfileTemplate.js
FrontEnd/coded/src/component/Search/Component/HashTag/Hashtag.js
FrontEnd/coded/src/component/Search/Component/HashTag/Hashtag.scss
FrontEnd/coded/src/component/Search/Component/User/User.js
FrontEnd/coded/src/component/Search/Component/User/User.scss
FrontEnd/coded/src/component/Search/Search.js
FrontEnd/coded/src/component/Search/Search.scss
FrontEnd/coded/src/pages/HomePageTemplate.js
FrontEnd/coded/src/pages/Weekly/Main/Component/Footer/Footer.js
FrontEnd/coded/src/pages/Weekly/Main/Component/Footer/Footer.scss
FrontEnd/coded/src/pages/Weekly/Main/Main.js
FrontEnd/coded/src/pages/Weekly/Main/Main.scss
FrontEnd/coded/src/pages/ootd/Main/Main.module.scss

lowercase1

---

FrontEnd/coded/src/component/Navbar/Navbar.js
FrontEnd/coded/src/component/Profile/Profile.js
FrontEnd/coded/src/component/Profile/Profile.module.scss

NaviBar의 날씨 표시하는 div 임시로 주석처리함

NaviBar의 날씨 표시하는 div 임시로 주석처리함

---

BackEnd/Coded/src/main/java/kh/coded/controllers/PhotoController.java
BackEnd/Coded/src/main/java/kh/coded/repositories/PhotoDAO.java
BackEnd/Coded/src/main/java/kh/coded/services/PhotoService.java
BackEnd/Coded/src/main/resources/mapper/photo-mapper.xml
FrontEnd/coded/package.json
FrontEnd/coded/src/App.js
FrontEnd/coded/src/component/Profile/Profile.js
FrontEnd/coded/src/component/Profile/Profile.module.scss
FrontEnd/coded/src/component/auth/AuthForm.js
FrontEnd/coded/src/test/CaroselTest.js
FrontEnd/coded/src/test/CaroselTest.scss
FrontEnd/coded/src/test/TestComponent.js
FrontEnd/coded/yarn.lock

upload CaroselTest

---

BackEnd/Coded/src/main/java/kh/coded/controllers/FeedPostController.java
BackEnd/Coded/src/main/java/kh/coded/repositories/FeedPostDAO.java
BackEnd/Coded/src/main/java/kh/coded/securityconfig/JwtAuthenticationFilter.java
BackEnd/Coded/src/main/java/kh/coded/services/FeedPostService.java
BackEnd/Coded/src/main/resources/mapper/feedpost-mapper.xml
FrontEnd/coded/src/component/Weekly/WeeklyFeedForm.js

feed list refactoring middle save4

weekly feed list refactoring

---

BackEnd/Coded/src/main/java/kh/coded/controllers/FeedPostController.java
BackEnd/Coded/src/main/java/kh/coded/repositories/FeedPostDAO.java
BackEnd/Coded/src/main/java/kh/coded/securityconfig/JwtAuthenticationFilter.java
BackEnd/Coded/src/main/java/kh/coded/services/FeedPostService.java
BackEnd/Coded/src/main/resources/mapper/feedpost-mapper.xml
FrontEnd/coded/src/component/FeedList/SearchedFeedList.js

search list refactoring

---

FrontEnd/coded/src/component/auth/AuthForm.module.scss
FrontEnd/coded/src/component/auth/AuthTemplate.js

authform 수정

---

FrontEnd/coded/src/component/Navbar/Navbar.scss
FrontEnd/coded/src/component/Profile/component/ChangePwModal.js
FrontEnd/coded/src/component/Profile/component/ChangePwModal.scss
FrontEnd/coded/src/pages/Ootd/Main/Modal.scss

update global css

---

FrontEnd/coded/src/component/FeedPostDetail/FeedPostDetail.js
FrontEnd/coded/src/component/FeedPostDetail/FeedPostDetail.module.scss

complete feedpostdetail

---

FrontEnd/coded/src/component/Footer/Footer.scss
FrontEnd/coded/src/component/Search/SearchBox.module.scss

검색창, footer 수정

---

FrontEnd/coded/src/component/Search/SearchBox.module.scss

자동완성 박스 수정

---

BackEnd/Coded/src/main/java/kh/coded/controllers/FeedPostController.java
BackEnd/Coded/src/main/java/kh/coded/repositories/FeedScrapDAO.java
BackEnd/Coded/src/main/java/kh/coded/securityconfig/SecurityConfiguration.java
BackEnd/Coded/src/main/resources/mapper/feedscrap-mapper.xml
FrontEnd/coded/src/component/FeedList/FeedList.js
FrontEnd/coded/src/component/FeedPostDetail/FeedPostDetail.js
FrontEnd/coded/src/component/FeedPostDetail/FeedPostDetail.module.scss
FrontEnd/coded/src/pages/Ootd/Main/Modal.js
FrontEnd/coded/src/pages/Ootd/Main/Modal.scss

좋아요, 스크랩 적용, 피드 리스트 완

---

FrontEnd/coded/src/App.js
FrontEnd/coded/src/component/Footer/Component/DeleteAccount/DeleteAccount.js

fix report

---

FrontEnd/coded/src/component/FeedPostDetail/FeedComment.module.scss
FrontEnd/coded/src/component/Profile/Profile.js

feedcomment style 추가 , profile useRef 추가

feedcomment style 추가 , profile useRef 추가

---

FrontEnd/coded/src/component/Profile/Profile.js
FrontEnd/coded/src/component/Profile/Profile.module.scss

마이페이지 스타일 수정

---

FrontEnd/coded/src/component/Navbar/Navbar.scss
FrontEnd/coded/src/pages/Ootd/Main/Modal.js

navBar 수정, modal 수정

---

BackEnd/Coded/src/main/java/kh/coded/config/WebMvcConfiguration.java
BackEnd/Coded/src/main/java/kh/coded/securityconfig/SecurityConfiguration.java
FrontEnd/coded/src/pages/DM/Component/ListElement.js

Hsj workspace

---

BackEnd/Coded/src/main/java/kh/coded/controllers/FeedPostController.java
BackEnd/Coded/src/main/java/kh/coded/repositories/FeedPostDAO.java
BackEnd/Coded/src/main/java/kh/coded/repositories/ReportDAO.java
BackEnd/Coded/src/main/java/kh/coded/services/FeedPostService.java
BackEnd/Coded/src/main/resources/mapper/feedpost-mapper.xml
FrontEnd/coded/src/pages/myPickPage/MyPickPage.scss

fix reportDAO

---

BackEnd/Coded/src/main/java/kh/coded/controllers/FollowController.java
BackEnd/Coded/src/main/java/kh/coded/repositories/FollowDAO.java
BackEnd/Coded/src/main/java/kh/coded/repositories/MemberDAO.java
BackEnd/Coded/src/main/java/kh/coded/securityconfig/SecurityConfiguration.java
BackEnd/Coded/src/main/java/kh/coded/services/FollowService.java
BackEnd/Coded/src/main/resources/mapper/follow-mapper.xml
BackEnd/Coded/src/main/resources/mapper/member-mapper.xml
FrontEnd/coded/src/component/FollowList/FollowList.js

팔로우, 팔로잉 기능 추가

---

BackEnd/Coded/src/main/java/kh/coded/services/FollowService.java
BackEnd/Coded/src/main/resources/mapper/member-mapper.xml

팔로워 리스트 수정

---

FrontEnd/coded/src/component/Search/SearchBox.js
FrontEnd/coded/src/pages/Ootd/Main/FeedModal.js
FrontEnd/coded/src/pages/Ootd/Main/FeedModal.scss

fix carousel

---

FrontEnd/coded/src/component/Report/component/ReportModal.js
FrontEnd/coded/src/pages/DM/Component/MenuButton.js

fix DMmodal

---

BackEnd/Coded/src/main/java/kh/coded/controllers/AuthenticationController.java
BackEnd/Coded/src/main/java/kh/coded/controllers/FollowController.java
BackEnd/Coded/src/main/java/kh/coded/repositories/FollowDAO.java
BackEnd/Coded/src/main/java/kh/coded/securityconfig/SecurityConfiguration.java
BackEnd/Coded/src/main/resources/mapper/member-mapper.xml
FrontEnd/coded/src/component/FeedList/FeedList.js
FrontEnd/coded/src/component/FeedPostDetail/FeedPostDetail.js
FrontEnd/coded/src/component/FollowList/FollowList.js
FrontEnd/coded/src/component/Weekly/WeeklyFeedForm.js
FrontEnd/coded/src/pages/myPickPage/MyPickPage.js

fix followPos

---

FrontEnd/coded/src/component/FeedPostDetail/FeedPostDetail.js
FrontEnd/coded/src/pages/Ootd/Main/FeedModal.js

UpdateFeedpost 완료

---

FrontEnd/coded/src/component/Common/ConfirmDialog.js
FrontEnd/coded/src/component/FeedList/SearchedFeedList.js
FrontEnd/coded/src/component/FeedPostDetail/FeedPostDetail.js
FrontEnd/coded/src/component/Footer/Component/DeleteAccount/DeleteAccount.js
FrontEnd/coded/src/component/Footer/Footer.js
FrontEnd/coded/src/component/Profile/Profile.js
FrontEnd/coded/src/pages/Ootd/Main/FeedModal.js

fix search, add loginConfirm 

---

FrontEnd/coded/src/component/FeedPostDetail/FeedComment.js
FrontEnd/coded/src/component/Report/component/ReportModal.js
FrontEnd/coded/src/component/Report/component/ReportModal.scss
FrontEnd/coded/src/pages/Ootd/Main/FeedModal.js

fix ReportFeed

---

FrontEnd/coded/src/component/FeedList/NoneSearchedBar.js

Useless Import Deleted

---

FrontEnd/coded/src/assets/ButtonAsset/BackButton.js
FrontEnd/coded/src/assets/ButtonAsset/ErrorConfirmPage.js
FrontEnd/coded/src/component/FeedList/NoneSearchedBar.js
FrontEnd/coded/src/component/Profile/Profile.js
FrontEnd/coded/src/component/Profile/Profile.module.scss
FrontEnd/coded/src/pages/DM/Component/sendBtn.js
FrontEnd/coded/src/pages/auth/Login/OAuthLastCallback.js
FrontEnd/coded/src/pages/myPickPage/MyPickPage.js
FrontEnd/coded/src/pages/myPickPage/MyPickPage.scss

add ErrorPage, BackButton

---

BackEnd/Coded/src/main/java/kh/coded/controllers/ChatController.java
BackEnd/Coded/src/main/java/kh/coded/securityconfig/SecurityConfiguration.java
FrontEnd/coded/src/assets/ButtonAsset/ChatButton.js
FrontEnd/coded/src/component/FeedPostDetail/FeedComment.js
FrontEnd/coded/src/component/Navbar/Navbar.js
FrontEnd/coded/src/component/Navbar/Navbar.scss
FrontEnd/coded/src/component/Report/component/ReportModal.js
FrontEnd/coded/src/component/Report/component/ReportModal.scss
FrontEnd/coded/src/pages/DM/Component/ChatBox.js
FrontEnd/coded/src/pages/DM/Component/SearchMember.js
FrontEnd/coded/src/pages/DM/Component/SearchMember.module.scss
FrontEnd/coded/src/pages/DM/DMList.js
FrontEnd/coded/src/pages/auth/Login/OAuthLastCallback.js
FrontEnd/coded/src/pages/myPickPage/MyPickPage.js
FrontEnd/coded/src/pages/myPickPage/MyPickPage.scss

update chatButton, fix DM

---

BackEnd/Coded/pom.xml
BackEnd/Coded/src/main/java/kh/coded/config/StompHandler.java
BackEnd/Coded/src/main/java/kh/coded/config/WebSocketConfig.java
BackEnd/Coded/src/main/java/kh/coded/controllers/StompController.java
FrontEnd/coded/src/pages/DM/DMList.js

dm alarm ing

---

FrontEnd/coded/src/component/Footer/Component/DeleteAccount/DeleteAccount.js
FrontEnd/coded/src/component/Footer/Footer.js
FrontEnd/coded/src/component/Footer/Footer.scss

fix footer

---

BackEnd/Coded/src/main/java/kh/coded/controllers/StompController.java
BackEnd/Coded/src/main/java/kh/coded/repositories/DMRoomDAO.java
BackEnd/Coded/src/main/java/kh/coded/services/DMRoomService.java
BackEnd/Coded/src/main/resources/mapper/DMRoom-mapper.xml
FrontEnd/coded/src/pages/DM/Component/SearchMember.module.scss

DM RoomDefence
